# Generated by Django 5.0.6 on 2024-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChordProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=10)),
                ('progression', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
